// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmvzymOwfhQ6xkaLO9ptw1k-ASz5rez38',
    appId: '1:1043507104127:web:72f7f600f8e19addb8724a',
    messagingSenderId: '1043507104127',
    projectId: 'apphgs-448df',
    authDomain: 'apphgs-448df.firebaseapp.com',
    storageBucket: 'apphgs-448df.appspot.com',
    measurementId: 'G-EVGLV0MQY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1IIlyYTKUIbfHVX6I5PuOWddJGXwh498',
    appId: '1:1043507104127:android:44a5b83a5b34de5ab8724a',
    messagingSenderId: '1043507104127',
    projectId: 'apphgs-448df',
    storageBucket: 'apphgs-448df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFEQ6OgaJXqzJYVghEA7eQsWmXeLdhyBA',
    appId: '1:1043507104127:ios:139286a625e1b890b8724a',
    messagingSenderId: '1043507104127',
    projectId: 'apphgs-448df',
    storageBucket: 'apphgs-448df.appspot.com',
    iosBundleId: 'com.example.projectTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFEQ6OgaJXqzJYVghEA7eQsWmXeLdhyBA',
    appId: '1:1043507104127:ios:139286a625e1b890b8724a',
    messagingSenderId: '1043507104127',
    projectId: 'apphgs-448df',
    storageBucket: 'apphgs-448df.appspot.com',
    iosBundleId: 'com.example.projectTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmvzymOwfhQ6xkaLO9ptw1k-ASz5rez38',
    appId: '1:1043507104127:web:ca73029ffccd11c6b8724a',
    messagingSenderId: '1043507104127',
    projectId: 'apphgs-448df',
    authDomain: 'apphgs-448df.firebaseapp.com',
    storageBucket: 'apphgs-448df.appspot.com',
    measurementId: 'G-7YCY44MGD4',
  );
}
